In [1]:
import intake

In [2]:
data_catalog = intake.open_esm_datastore('/g/data/dk92/catalog/v2/esm/barra2-ob53/catalog.json')

/g/data/xv83/dbi599/miniconda3/envs/intake/lib/python3.13/site-packages/fastprogress/fastprogress.py:107: UserWarning: Couldn't import ipywidgets properly, progress bar will use console behavior
  warn("Couldn't import ipywidgets properly, progress bar will use console behavior")

In [3]:
data_catalog

In [4]:
data_catalog.df['variable_id'].unique()

array(['clh', 'ua500', 'va1000', 'rsdsdir', 'tasmin', 'vas', 'hus700',
       'ta150m', 'wsgsmax', 'rsus', 'va1500m', 'ta500', 'tasmean', 'hurs',
       'mrsos', 'zg925', 'va200', 'zg700', 'va150m', 'huss', 'rlds',
       'ua925', 'zg500', 'wa600', 'ta200', 'uasmax', 'va850', 'ta1500m',
       'va400', 'ta100m', 'rsdt', 'rluscs', 'va100m', 'CIN', 'ta250m',
       'tas', 'ps', 'wa200', 'ta70', 'tsl', 'mrso', 'va30', 'ta20',
       'va50', 'va20', 'zg250', 'ua10', 'hus30', 'wa100', 'ua250',
       'hus20', 'wa30', 'zg1000', 'psl', 'ts', 'rsutcs', 'mrros', 'rsut',
       'cll', 'ua150m', 'tasmax', 'ua400', 'ta600', 'va50m', 'ua850',
       'sfcWind', 'rldscs', 'twiso', 'wa850', 'ta50m', 'clwvi', 'zg850',
       'mrfsos', 'hus850', 'ta1000', 'zg10', 'va925', 'hus10', 'wa10',
       'prsn', 'hus70', 'rlut', 'rlus', 'wa500', 'ta30', 'va200m',
       'zg300', 'mrfso', 'ua250m', 'clt', 'ua1000', 'z0', 'wa150',
       'ta400', 'twpse', 'wa300', 'va250m', 'omega500', 'hfls', 'rlutcs',
       'wa50', 'evspsbl', 'wa700', 'sund', 'uas', 'hus500', 'evspsblpot',
       'mrfsol', 'va500', 'hus200', 'hus400', 'wa1000', 'ta300', 'zg200',
       'ua100m', 'sic', 'hus600', 'zg400', 'ta925', 'prw', 'hus150',
       'zg600', 'ta850', 'clivi', 'ua700', 'ua20', 'va150', 'ua600',
       'va250', 'ua50', 'prc', 'ua50m', 'clm', 'va100', 'hus1000', 'mrro',
       'va700', 'ta10', 'ua200m', 'rsds', 'ua30', 'ua150', 'zmla', 'snd',
       'ta200m', 'hus100', 'va300', 'CAPE', 'wa400', 'ua200', 'ta700',
       'ta250', 'zg20', 'ta100', 'snw', 'sfcWindmax', 'MULPLpres',
       'MLCAPE', 'MUVTEmean', 'MUCIN', 'MULPLtemp', 'V03mean', 'SRH03l',
       'BWD01', 'LR01', 'SRH01l', 'U06mean', 'MULPL', 'EMLbase', 'BWD06',
       'SRH01r', 'WBFZL', 'BWD09', 'RH24mean', 'VESMadv', 'USMadv',
       'VSMdev', 'MAULbase', 'MLLMB', 'ESRHl', 'MLVTEmax', 'MLCAPEx',
       'VEILmean', 'UEILmean', 'UESMadv', 'BWD09dir', 'MULCL', 'V06mean',
       'EFFCAPE', 'USMdev', 'SF', 'ESRHr', 'MULPLmixr', 'MULFC',
       'U0500mean', 'MUVTEmax', 'LR36', 'BWD03', 'U03mean', 'MAULlapse',
       'MLSCLR', 'MUVTEm10', 'MLCAPbase', 'SRH0500l', 'LR03', 'V0500mean',
       'MULCLtemp', 'RH01mean', 'MUVTEm20', 'EMLlapse', 'HGZdepth',
       'MLEL', 'RH36mean', 'LR24', 'BWD01dir', 'PW', 'MLCAPdepth',
       'MUELtemp', 'EBWD', 'VSMadv', 'BWD06dir', 'SRH03r', 'MLSCRHmean',
       'MLCIN', 'DPL', 'MLCIN1', 'MAULdepth', 'MLLPLmixr', 'EBWDdir',
       'EILbase', 'VANVmean', 'MULMB', 'EMLdepth', 'MUCAPEm10m30',
       'RH03mean', 'MLCAPE03', 'CRZdepth', 'LR75', 'U01mean', 'V01mean',
       'EFFCIN', 'MLLPLtemp', 'SRH0500r', 'MLVTEmean', 'CAPEmax',
       'CINmax', 'ua300', 'rsuscs', 'ua1500m', 'va600', 'hus300',
       'hus950', 'hus925', 'rsdscs', 'pr', 'wa925', 'vasmean',
       'MUCAPE0m20', 'MUEL', 'MLLCL', 'BWD03dir', 'hfss', 'orog', 'snm',
       'zg70', 'wa250', 'tauu', 'va70', 'hus250', 'va10', 'twisomax',
       'twpsemax', 'wa20', 'tauv', 'ua100', 'ua70', 'hus50', 'mrsol',
       'zg50', 'zg30', 'ta150', 'wa70', 'MUCAPE', 'EILdepth', 'ua975',
       'va750', 'wap300', 'zg150', 'zg100', 'ta50', 'maxcolrefl',
       'qfluxu', 'qfluxv', 'prhmax', 'ta950', 'vasmax', 'uasmean',
       'ta750', 'wap500', 'hus975', 'hus900', 'helicitymax', 'wap925',
       'ta975', 'prga', 'wap400', 'wap750', 'zg950', 'va950', 'ua950',
       'hus750', 'wsgs', 'wa750', 'prra', 'coltotwetm', 'wap700', 'ta800',
       'wa900', 'zg900', 'wa800', 'wap900', 'wap850', 'tsmean', 'wap800',
       'wap600', 'maxcolwa', 'hus800', 'va975', 'zg975', 'wa950', 'ua800',
       'wap975', 'prsnmax', 'zg750', 'fogfraction', 'helicitymin',
       'ua750', 'visibility', 'wap200', 'zg800', 'wa975', 'ta900', 'ztp',
       'coltotdrym', 'sfcMoisflx', 'wap20', 'MUCAPEmax', 'ua900', 'wap70',
       'wap100', 'wap10', 'wap250', 'wap1000', 'wap150', 'wap50', 'va900',
       'wap950', 'wap30', 'va800', 'UANVmean', 'DCAPE', 'MLLFC', 'FZL',
       'flashrate', 'rsdsdif', 'helicity', 'radrefl1km', 'rss', 'ares',
       'soildrainage', 'throughfall', 'cw', 'MUCINmax',
       'sfcWind10minmean', 'sftlf'], dtype=object)

In [5]:
data_catalog.df['domain_id'].unique()

array(['AUS-22', 'AUS-11', 'AUST-11', 'AUST-22', 'AUST-04'], dtype=object)

In [6]:
data_catalog.df['version'].unique()

array(['v20240809', 'v20240705', 'v20241112', 'v20241004', 'v20240516',
       'v20231001'], dtype=object)

In [7]:
data_catalog.df['freq'].unique()

array(['1hr', '3hr', 'mon', 'day', 'fx', '10min', '20min'], dtype=object)

In [11]:
query = dict(
    variable_id=['pr'],
    freq=['day'],
    domain_id=['AUS-11'],
)

In [12]:
catalog_subset = data_catalog.search(**query)

In [13]:
catalog_subset

In [14]:
catalog_subset.df

,path,file_type,project_id,activity_id,domain_id,RCM_institution_id,driving_source_id,driving_experiment_id,driving_variant_label,source_id,version_realisation,freq,variable_id,version,start_time,end_time,time_range
0,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,199606.0,199606.0,199606-199606
1,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,199410.0,199410.0,199410-199410
2,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,199912.0,199912.0,199912-199912
3,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,198403.0,198403.0,198403-198403
4,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,200912.0,200912.0,200912-200912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,199501.0,199501.0,199501-199501
545,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,201002.0,201002.0,201002-201002
546,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,199308.0,199308.0,199308-199308
547,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,199411.0,199411.0,199411-199411
548,/g/data/ob53/BARRA2/output/reanalysis/AUS-11/B...,f,output,reanalysis,AUS-11,BOM,ERA5,historical,hres,BARRA-R2,v1,day,pr,v20240809,198607.0,198607.0,198607-198607

In [16]:
sorted(catalog_subset.df['time_range'].unique())

['197901-197901',
 '197902-197902',
 '197903-197903',
 '197904-197904',
 '197905-197905',
 '197906-197906',
 '197907-197907',
 '197908-197908',
 '197909-197909',
 '197910-197910',
 '197911-197911',
 '197912-197912',
 '198001-198001',
 '198002-198002',
 '198003-198003',
 '198004-198004',
 '198005-198005',
 '198006-198006',
 '198007-198007',
 '198008-198008',
 '198009-198009',
 '198010-198010',
 '198011-198011',
 '198012-198012',
 '198101-198101',
 '198102-198102',
 '198103-198103',
 '198104-198104',
 '198105-198105',
 '198106-198106',
 '198107-198107',
 '198108-198108',
 '198109-198109',
 '198110-198110',
 '198111-198111',
 '198112-198112',
 '198201-198201',
 '198202-198202',
 '198203-198203',
 '198204-198204',
 '198205-198205',
 '198206-198206',
 '198207-198207',
 '198208-198208',
 '198209-198209',
 '198210-198210',
 '198211-198211',
 '198212-198212',
 '198301-198301',
 '198302-198302',
 '198303-198303',
 '198304-198304',
 '198305-198305',
 '198306-198306',
 '198307-198307',
 '198308-198308',
 '198309-198309',
 '198310-198310',
 '198311-198311',
 '198312-198312',
 '198401-198401',
 '198402-198402',
 '198403-198403',
 '198404-198404',
 '198405-198405',
 '198406-198406',
 '198407-198407',
 '198408-198408',
 '198409-198409',
 '198410-198410',
 '198411-198411',
 '198412-198412',
 '198501-198501',
 '198502-198502',
 '198503-198503',
 '198504-198504',
 '198505-198505',
 '198506-198506',
 '198507-198507',
 '198508-198508',
 '198509-198509',
 '198510-198510',
 '198511-198511',
 '198512-198512',
 '198601-198601',
 '198602-198602',
 '198603-198603',
 '198604-198604',
 '198605-198605',
 '198606-198606',
 '198607-198607',
 '198608-198608',
 '198609-198609',
 '198610-198610',
 '198611-198611',
 '198612-198612',
 '198701-198701',
 '198702-198702',
 '198703-198703',
 '198704-198704',
 '198705-198705',
 '198706-198706',
 '198707-198707',
 '198708-198708',
 '198709-198709',
 '198710-198710',
 '198711-198711',
 '198712-198712',
 '198801-198801',
 '198802-198802',
 '198803-198803',
 '198804-198804',
 '198805-198805',
 '198806-198806',
 '198807-198807',
 '198808-198808',
 '198809-198809',
 '198810-198810',
 '198811-198811',
 '198812-198812',
 '198901-198901',
 '198902-198902',
 '198903-198903',
 '198904-198904',
 '198905-198905',
 '198906-198906',
 '198907-198907',
 '198908-198908',
 '198909-198909',
 '198910-198910',
 '198911-198911',
 '198912-198912',
 '199001-199001',
 '199002-199002',
 '199003-199003',
 '199004-199004',
 '199005-199005',
 '199006-199006',
 '199007-199007',
 '199008-199008',
 '199009-199009',
 '199010-199010',
 '199011-199011',
 '199012-199012',
 '199101-199101',
 '199102-199102',
 '199103-199103',
 '199104-199104',
 '199105-199105',
 '199106-199106',
 '199107-199107',
 '199108-199108',
 '199109-199109',
 '199110-199110',
 '199111-199111',
 '199112-199112',
 '199201-199201',
 '199202-199202',
 '199203-199203',
 '199204-199204',
 '199205-199205',
 '199206-199206',
 '199207-199207',
 '199208-199208',
 '199209-199209',
 '199210-199210',
 '199211-199211',
 '199212-199212',
 '199301-199301',
 '199302-199302',
 '199303-199303',
 '199304-199304',
 '199305-199305',
 '199306-199306',
 '199307-199307',
 '199308-199308',
 '199309-199309',
 '199310-199310',
 '199311-199311',
 '199312-199312',
 '199401-199401',
 '199402-199402',
 '199403-199403',
 '199404-199404',
 '199405-199405',
 '199406-199406',
 '199407-199407',
 '199408-199408',
 '199409-199409',
 '199410-199410',
 '199411-199411',
 '199412-199412',
 '199501-199501',
 '199502-199502',
 '199503-199503',
 '199504-199504',
 '199505-199505',
 '199506-199506',
 '199507-199507',
 '199508-199508',
 '199509-199509',
 '199510-199510',
 '199511-199511',
 '199512-199512',
 '199601-199601',
 '199602-199602',
 '199603-199603',
 '199604-199604',
 '199605-199605',
 '199606-199606',
 '199607-199607',
 '199608-199608',
 '199609-199609',
 '199610-199610',
 '199611-199611',
 '199612-199612',
 '199701-199701',
 '199702-199702',
 '199703-199703',
 '199704-199704',
 '199705-199705',
 '199706-199706',
 '199707-199707',
 '199708-199708',
 '199709-199709',
 '199710-199710',
 '199711-199711',
 '199712-199712',
 '199801-199801',
 '199802-199802',
 '199803-199803',
 '199804-199804',
 '199805-199805',
 '199806-199806',
 '199807-199807',
 '199808-199808',
 '199809-199809',
 '199810-199810',
 '199811-199811',
 '199812-199812',
 '199901-199901',
 '199902-199902',
 '199903-199903',
 '199904-199904',
 '199905-199905',
 '199906-199906',
 '199907-199907',
 '199908-199908',
 '199909-199909',
 '199910-199910',
 '199911-199911',
 '199912-199912',
 '200001-200001',
 '200002-200002',
 '200003-200003',
 '200004-200004',
 '200005-200005',
 '200006-200006',
 '200007-200007',
 '200008-200008',
 '200009-200009',
 '200010-200010',
 '200011-200011',
 '200012-200012',
 '200101-200101',
 '200102-200102',
 '200103-200103',
 '200104-200104',
 '200105-200105',
 '200106-200106',
 '200107-200107',
 '200108-200108',
 '200109-200109',
 '200110-200110',
 '200111-200111',
 '200112-200112',
 '200201-200201',
 '200202-200202',
 '200203-200203',
 '200204-200204',
 '200205-200205',
 '200206-200206',
 '200207-200207',
 '200208-200208',
 '200209-200209',
 '200210-200210',
 '200211-200211',
 '200212-200212',
 '200301-200301',
 '200302-200302',
 '200303-200303',
 '200304-200304',
 '200305-200305',
 '200306-200306',
 '200307-200307',
 '200308-200308',
 '200309-200309',
 '200310-200310',
 '200311-200311',
 '200312-200312',
 '200401-200401',
 '200402-200402',
 '200403-200403',
 '200404-200404',
 '200405-200405',
 '200406-200406',
 '200407-200407',
 '200408-200408',
 '200409-200409',
 '200410-200410',
 '200411-200411',
 '200412-200412',
 '200501-200501',
 '200502-200502',
 '200503-200503',
 '200504-200504',
 '200505-200505',
 '200506-200506',
 '200507-200507',
 '200508-200508',
 '200509-200509',
 '200510-200510',
 '200511-200511',
 '200512-200512',
 '200601-200601',
 '200602-200602',
 '200603-200603',
 '200604-200604',
 '200605-200605',
 '200606-200606',
 '200607-200607',
 '200608-200608',
 '200609-200609',
 '200610-200610',
 '200611-200611',
 '200612-200612',
 '200701-200701',
 '200702-200702',
 '200703-200703',
 '200704-200704',
 '200705-200705',
 '200706-200706',
 '200707-200707',
 '200708-200708',
 '200709-200709',
 '200710-200710',
 '200711-200711',
 '200712-200712',
 '200801-200801',
 '200802-200802',
 '200803-200803',
 '200804-200804',
 '200805-200805',
 '200806-200806',
 '200807-200807',
 '200808-200808',
 '200809-200809',
 '200810-200810',
 '200811-200811',
 '200812-200812',
 '200901-200901',
 '200902-200902',
 '200903-200903',
 '200904-200904',
 '200905-200905',
 '200906-200906',
 '200907-200907',
 '200908-200908',
 '200909-200909',
 '200910-200910',
 '200911-200911',
 '200912-200912',
 '201001-201001',
 '201002-201002',
 '201003-201003',
 '201004-201004',
 '201005-201005',
 '201006-201006',
 '201007-201007',
 '201008-201008',
 '201009-201009',
 '201010-201010',
 '201011-201011',
 '201012-201012',
 '201101-201101',
 '201102-201102',
 '201103-201103',
 '201104-201104',
 '201105-201105',
 '201106-201106',
 '201107-201107',
 '201108-201108',
 '201109-201109',
 '201110-201110',
 '201111-201111',
 '201112-201112',
 '201201-201201',
 '201202-201202',
 '201203-201203',
 '201204-201204',
 '201205-201205',
 '201206-201206',
 '201207-201207',
 '201208-201208',
 '201209-201209',
 '201210-201210',
 '201211-201211',
 '201212-201212',
 '201301-201301',
 '201302-201302',
 '201303-201303',
 '201304-201304',
 '201305-201305',
 '201306-201306',
 '201307-201307',
 '201308-201308',
 '201309-201309',
 '201310-201310',
 '201311-201311',
 '201312-201312',
 '201401-201401',
 '201402-201402',
 '201403-201403',
 '201404-201404',
 '201405-201405',
 '201406-201406',
 '201407-201407',
 '201408-201408',
 '201409-201409',
 '201410-201410',
 '201411-201411',
 '201412-201412',
 '201501-201501',
 '201502-201502',
 '201503-201503',
 '201504-201504',
 '201505-201505',
 '201506-201506',
 '201507-201507',
 '201508-201508',
 '201509-201509',
 '201510-201510',
 '201511-201511',
 '201512-201512',
 '201601-201601',
 '201602-201602',
 '201603-201603',
 '201604-201604',
 '201605-201605',
 '201606-201606',
 '201607-201607',
 '201608-201608',
 '201609-201609',
 '201610-201610',
 '201611-201611',
 '201612-201612',
 '201701-201701',
 '201702-201702',
 '201703-201703',
 '201704-201704',
 '201705-201705',
 '201706-201706',
 '201707-201707',
 '201708-201708',
 '201709-201709',
 '201710-201710',
 '201711-201711',
 '201712-201712',
 '201801-201801',
 '201802-201802',
 '201803-201803',
 '201804-201804',
 '201805-201805',
 '201806-201806',
 '201807-201807',
 '201808-201808',
 '201809-201809',
 '201810-201810',
 '201811-201811',
 '201812-201812',
 '201901-201901',
 '201902-201902',
 '201903-201903',
 '201904-201904',
 '201905-201905',
 '201906-201906',
 '201907-201907',
 '201908-201908',
 '201909-201909',
 '201910-201910',
 '201911-201911',
 '201912-201912',
 '202001-202001',
 '202002-202002',
 '202003-202003',
 '202004-202004',
 '202005-202005',
 '202006-202006',
 '202007-202007',
 '202008-202008',
 '202009-202009',
 '202010-202010',
 '202011-202011',
 '202012-202012',
 '202101-202101',
 '202102-202102',
 '202103-202103',
 '202104-202104',
 '202105-202105',
 '202106-202106',
 '202107-202107',
 '202108-202108',
 '202109-202109',
 '202110-202110',
 '202111-202111',
 '202112-202112',
 '202201-202201',
 '202202-202202',
 '202203-202203',
 '202204-202204',
 '202205-202205',
 '202206-202206',
 '202207-202207',
 '202208-202208',
 '202209-202209',
 '202210-202210',
 '202211-202211',
 '202212-202212',
 '202301-202301',
 '202302-202302',
 '202303-202303',
 '202304-202304',
 '202305-202305',
 '202306-202306',
 '202307-202307',
 '202308-202308',
 '202309-202309',
 '202310-202310',
 '202311-202311',
 '202312-202312',
 '202401-202401',
 '202402-202402',
 '202403-202403',
 '202404-202404',
 '202405-202405',
 '202406-202406',
 '202407-202407',
 '202408-202408',
 '202409-202409']

In [ ]:
dsets = catalog_subset.to_dataset_dict()

--> The keys in the returned dictionary of datasets are constructed as follows:
	'file_type.project_id.activity_id.domain_id.RCM_institution_id.driving_source_id.driving_experiment_id.driving_variant_label.source_id.version_realisation.freq.variable_id.version'
 |----------------------------------------| 0.00% [0/1 00:00<?]